import os
import shutil
import struct
import zlib
from pathlib import Path
from typing import Optional
from dataclasses import dataclass

# Try to import PIL for EXIF data
try:
    from PIL import Image
    from PIL.ExifTags import TAGS
    PIL_AVAILABLE = True
except ImportError:
    PIL_AVAILABLE = False
    print("Warning: Pillow not installed. Install with: pip install Pillow")
    print("Some metadata detection features will be limited.\n")


# Known AI tool signatures to look for in metadata
AI_SIGNATURES = [
    # Stable Diffusion / ComfyUI / A1111
    "stable diffusion",
    "stablediffusion", 
    "sd_model",
    "comfyui",
    "comfy",
    "automatic1111",
    "a1111",
    "invokeai",
    "novelai",
    "nai diffusion",
    "dreamstudio",
    "stability.ai",
    "sdxl",
    "sd 1.5",
    "sd 2.1",
    "flux",
    
    # Generation parameters (common in SD)
    "cfg scale",
    "cfg_scale",
    "sampler:",
    "steps:",
    "seed:",
    "negative prompt",
    "lora:",
    "embedding:",
    "checkpoint:",
    "vae:",
    "clip skip",
    
    # DALL-E / OpenAI / ChatGPT
    "dall-e",
    "dalle",
    "dall-e-3",
    "dalle-3",
    "openai",
    "chatgpt",
    "gpt-4",
    "c2pa",
    "contentcredentials",
    "made with ai",
    
    # Google Gemini / Imagen
    "gemini",
    "google gemini",
    "imagen",
    "google imagen",
    "google ai",
    "made by google",
    "iptc.org/ai",
    "digitalsourcetype",
    "trainedmachine",
    
    # Midjourney
    "midjourney",
    "mj",
    "--ar ",  # Midjourney aspect ratio flag
    "--v ",   # Midjourney version flag
    
    # Other AI tools
    "leonardo.ai",
    "leonardo ai",
    "bing image creator",
    "copilot designer",
    "adobe firefly",
    "firefly",
    "runway",
    "nightcafe",
    "artbreeder",
    "deepai",
    "starryai",
    "craiyon",
    "wombo dream",
    "jasper art",
    "getimg.ai",
    "playground ai",
    "dreamlike",
    "lexica",
    "prompthero",
    
    # Generic AI indicators
    "ai generated",
    "ai-generated",
    "generated by ai",
    "created with ai",
    "text2image",
    "text-to-image",
    "txt2img",
    "img2img",
    "inpainting",
    "controlnet",
    "lora",
    "dreambooth",
    
    # Model names
    "realistic vision",
    "deliberate",
    "counterfeit",
    "anything v",
    "dreamshaper",
    "protogen",
    "basil mix",
    "abyss orange",
    "majicmix",
    "chilloutmix",
    "meinamix",
]

# File extensions to process
IMAGE_EXTENSIONS = {'.png', '.jpg', '.jpeg', '.webp', '.gif', '.bmp', '.tiff', '.tif'}

# Common AI-generated image dimensions (width, height)
# These are used as additional heuristics when no metadata is found
AI_IMAGE_DIMENSIONS = {
    # DALL-E 3 / ChatGPT standard sizes
    (1024, 1024),  # Square
    (1024, 1792),  # Portrait
    (1792, 1024),  # Landscape
    # DALL-E 2 sizes
    (512, 512),
    (256, 256),
    # Midjourney common sizes
    (1456, 816),  # 16:9 upscaled
    (816, 1456),  # 9:16 upscaled
    (1024, 576),  # 16:9
    (576, 1024),  # 9:16
    # Gemini / ChatGPT additional aspect ratios
    (1024, 768),  # 4:3
    (768, 1024),  # 3:4
    (1024, 682),  # 3:2 (common ChatGPT landscape)
    (682, 1024),  # 2:3
    (1024, 683),  # 3:2 variant
    (683, 1024),  # 2:3 variant
    # More common AI resolutions
    (1280, 720),  # HD 16:9
    (720, 1280),  # HD 9:16
    (1536, 1024), # 3:2 larger
    (1024, 1536), # 2:3 larger
    (2048, 2048), # Large square (upscaled)
}


@dataclass
class ScanResult:
    """Result of scanning an image for AI signatures"""
    filepath: Path
    is_ai: bool
    confidence: str  # "high", "medium", "low", "none"
    detected_signatures: list
    metadata_source: str  # Where the signature was found
    ai_tool: str  # Identified AI tool: "ChatGPT", "Gemini", "Stable Diffusion", "Midjourney", etc.


def read_png_chunks(filepath: Path) -> dict:
    """
    Read PNG text chunks directly - this is where Stable Diffusion 
    stores generation parameters
    """
    chunks = {}
    
    try:
        with open(filepath, 'rb') as f:
            # Check PNG signature
            signature = f.read(8)
            if signature != b'\x89PNG\r\n\x1a\n':
                return chunks
            
            while True:
                # Read chunk header
                chunk_header = f.read(8)
                if len(chunk_header) < 8:
                    break
                    
                length = struct.unpack('>I', chunk_header[:4])[0]
                chunk_type = chunk_header[4:8].decode('ascii', errors='ignore')
                
                # Read chunk data
                chunk_data = f.read(length)
                
                # Read CRC
                f.read(4)
                
                # Text chunks contain metadata
                if chunk_type in ('tEXt', 'iTXt', 'zTXt'):
                    try:
                        if chunk_type == 'tEXt':
                            # Simple text: keyword\0text
                            null_pos = chunk_data.find(b'\x00')
                            if null_pos != -1:
                                key = chunk_data[:null_pos].decode('latin-1')
                                value = chunk_data[null_pos+1:].decode('latin-1', errors='ignore')
                                chunks[key] = value
                                
                        elif chunk_type == 'zTXt':
                            # Compressed text: keyword\0compression_method\0compressed_text
                            null_pos = chunk_data.find(b'\x00')
                            if null_pos != -1:
                                key = chunk_data[:null_pos].decode('latin-1')
                                # Skip compression method byte
                                compressed = chunk_data[null_pos+2:]
                                try:
                                    value = zlib.decompress(compressed).decode('utf-8', errors='ignore')
                                    chunks[key] = value
                                except:
                                    pass
                                    
                        elif chunk_type == 'iTXt':
                            # International text - more complex
                            null_pos = chunk_data.find(b'\x00')
                            if null_pos != -1:
                                key = chunk_data[:null_pos].decode('utf-8', errors='ignore')
                                # Parse the rest (compression flag, method, language, translated keyword, text)
                                rest = chunk_data[null_pos+1:]
                                if len(rest) >= 2:
                                    compression_flag = rest[0]
                                    # Find the text after null terminators
                                    parts = rest[2:].split(b'\x00', 2)
                                    if len(parts) >= 3:
                                        text = parts[2]
                                        if compression_flag:
                                            try:
                                                text = zlib.decompress(text)
                                            except:
                                                pass
                                        chunks[key] = text.decode('utf-8', errors='ignore') if isinstance(text, bytes) else text
                    except Exception:
                        pass
                        
                # IEND marks end of PNG
                if chunk_type == 'IEND':
                    break
                    
    except Exception as e:
        pass
        
    return chunks


def get_exif_data(filepath: Path) -> dict:
    """Extract EXIF metadata from image using PIL"""
    exif_data = {}
    
    if not PIL_AVAILABLE:
        return exif_data
        
    try:
        with Image.open(filepath) as img:
            # Get standard EXIF
            exif = img._getexif()
            if exif:
                for tag_id, value in exif.items():
                    tag = TAGS.get(tag_id, tag_id)
                    if isinstance(value, bytes):
                        value = value.decode('utf-8', errors='ignore')
                    exif_data[str(tag)] = str(value)
            
            # Get PNG info (where SD stores data)
            if hasattr(img, 'info'):
                for key, value in img.info.items():
                    if isinstance(value, bytes):
                        value = value.decode('utf-8', errors='ignore')
                    exif_data[f"PNG:{key}"] = str(value)
                    
            # Get XMP data if available
            if hasattr(img, 'applist'):
                for segment, content in img.applist:
                    if segment == 'APP1' and b'http://ns.adobe.com/xap/' in content:
                        exif_data['XMP'] = content.decode('utf-8', errors='ignore')
                        
    except Exception as e:
        pass
        
    return exif_data


def check_gemini_watermark(filepath: Path) -> bool:
    """
    Check for Gemini's watermark (white 4-pointed star in bottom-right corner).
    Returns True if watermark is likely detected.
    """
    if not PIL_AVAILABLE:
        return False
    
    try:
        with Image.open(filepath) as img:
            # Convert to RGB if needed
            if img.mode != 'RGB':
                img = img.convert('RGB')
            
            width, height = img.size
            
            # Check bottom-right corner (where Gemini puts its watermark)
            # Watermark is typically in the bottom 5% and right 5% of image
            corner_size = min(int(width * 0.08), int(height * 0.08), 80)
            
            # Crop bottom-right corner
            corner = img.crop((
                width - corner_size,
                height - corner_size,
                width,
                height
            ))
            
            # Look for bright white pixels in a pattern (the star is white)
            # Count very bright pixels (potential watermark)
            pixels = list(corner.getdata())
            white_count = 0
            near_white_count = 0
            
            for r, g, b in pixels:
                # Check for white/near-white pixels
                if r > 240 and g > 240 and b > 240:
                    white_count += 1
                elif r > 200 and g > 200 and b > 200:
                    near_white_count += 1
            
            total_pixels = len(pixels)
            white_ratio = white_count / total_pixels if total_pixels > 0 else 0
            
            # Gemini watermark typically has a specific pattern
            # Not too many white pixels (it's subtle) but enough to be noticeable
            # The star shape creates a specific white pixel density
            if 0.02 < white_ratio < 0.25 and white_count > 20:
                return True
                
    except Exception:
        pass
    
    return False


def check_ai_dimensions(filepath: Path) -> tuple:
    """
    Check if image has common AI-generated dimensions.
    Returns (is_ai_dimension, width, height)
    """
    if not PIL_AVAILABLE:
        return (False, 0, 0)
    
    try:
        with Image.open(filepath) as img:
            size = img.size
            is_ai_dim = size in AI_IMAGE_DIMENSIONS
            return (is_ai_dim, size[0], size[1])
    except Exception:
        return (False, 0, 0)


def identify_ai_tool(detected_signatures: list, all_text: str) -> str:
    """
    Identify the specific AI tool based on detected signatures
    Returns the most likely AI tool that generated the image
    """
    all_text_lower = all_text.lower()
    signatures_lower = [s.lower() for s in detected_signatures]
    
    # ChatGPT / DALL-E 3 indicators
    chatgpt_indicators = [
        'chatgpt', 'gpt-4', 'dall-e-3', 'dalle-3', 'c2pa', 
        'contentcredentials', 'made with ai'
    ]
    if any(ind in all_text_lower for ind in chatgpt_indicators):
        return "ChatGPT (DALL-E 3)"
    
    # Check for OpenAI/DALL-E (older versions or generic)
    if any(ind in all_text_lower for ind in ['openai', 'dall-e', 'dalle']):
        return "DALL-E (OpenAI)"
    
    # Google Gemini / Imagen indicators
    gemini_indicators = [
        'gemini', 'google gemini', 'imagen', 'google imagen', 
        'google ai', 'made by google', 'iptc.org/ai', 
        'digitalsourcetype', 'trainedmachine'
    ]
    if any(ind in all_text_lower for ind in gemini_indicators):
        return "Google Gemini"
    
    # Midjourney indicators
    midjourney_indicators = ['midjourney', '--ar ', '--v ', 'mj']
    if any(ind in all_text_lower for ind in midjourney_indicators):
        return "Midjourney"
    
    # ComfyUI indicators
    if 'comfyui' in all_text_lower or 'comfy' in all_text_lower or 'workflow' in all_text_lower:
        return "ComfyUI"
    
    # Automatic1111 / A1111 indicators
    a1111_indicators = ['automatic1111', 'a1111', 'parameters']
    if any(ind in all_text_lower for ind in a1111_indicators):
        return "Stable Diffusion (A1111)"
    
    # NovelAI indicators
    if 'novelai' in all_text_lower or 'nai diffusion' in all_text_lower:
        return "NovelAI"
    
    # InvokeAI indicators
    if 'invokeai' in all_text_lower:
        return "InvokeAI"
    
    # Adobe Firefly indicators
    if 'firefly' in all_text_lower or 'adobe' in all_text_lower:
        return "Adobe Firefly"
    
    # Bing Image Creator / Copilot Designer
    if 'bing image creator' in all_text_lower or 'copilot designer' in all_text_lower:
        return "Bing Image Creator"
    
    # Leonardo.AI indicators
    if 'leonardo' in all_text_lower:
        return "Leonardo.AI"
    
    # Generic Stable Diffusion detection
    sd_indicators = [
        'stable diffusion', 'stablediffusion', 'sd_model', 'sdxl', 
        'sd 1.5', 'sd 2.1', 'flux', 'cfg scale', 'cfg_scale',
        'sampler:', 'steps:', 'seed:', 'negative prompt', 'lora:',
        'checkpoint:', 'vae:', 'clip skip', 'txt2img', 'img2img',
        'controlnet', 'lora', 'dreambooth'
    ]
    if any(ind in all_text_lower for ind in sd_indicators):
        return "Stable Diffusion"
    
    # Check for known model names (SD-based)
    model_names = [
        'realistic vision', 'deliberate', 'counterfeit', 'anything v',
        'dreamshaper', 'protogen', 'basil mix', 'abyss orange',
        'majicmix', 'chilloutmix', 'meinamix'
    ]
    if any(name in all_text_lower for name in model_names):
        return "Stable Diffusion"
    
    # Other known AI tools
    if 'nightcafe' in all_text_lower:
        return "NightCafe"
    if 'artbreeder' in all_text_lower:
        return "Artbreeder"
    if 'deepai' in all_text_lower:
        return "DeepAI"
    if 'starryai' in all_text_lower:
        return "StarryAI"
    if 'craiyon' in all_text_lower:
        return "Craiyon"
    if 'wombo' in all_text_lower:
        return "Wombo Dream"
    if 'runway' in all_text_lower:
        return "Runway"
    if 'playground' in all_text_lower:
        return "Playground AI"
    if 'dreamlike' in all_text_lower:
        return "Dreamlike"
    if 'lexica' in all_text_lower:
        return "Lexica"
    
    # Generic AI detection
    if any(ind in all_text_lower for ind in ['ai generated', 'ai-generated', 'generated by ai', 'created with ai', 'text2image', 'text-to-image']):
        return "Unknown AI Tool"
    
    return "Unknown AI Tool"


def check_for_ai_signatures(metadata: dict, filepath: Path) -> ScanResult:
    """Check metadata for AI generation signatures"""
    detected = []
    sources = []
    
    # Combine all metadata values into searchable text
    all_text = ""
    for key, value in metadata.items():
        text = f"{key}: {value}".lower()
        all_text += text + "\n"
        
        # Check each signature
        for signature in AI_SIGNATURES:
            if signature.lower() in text:
                detected.append(signature)
                sources.append(key)
    
    # Special checks for specific patterns
    
    # Check for C2PA / Content Credentials (ChatGPT/DALL-E 3)
    if any(key.lower() in ['c2pa', 'contentcredentials', 'jumbf'] for key in metadata.keys()):
        detected.append('c2pa content credentials')
        sources.append('Content Credentials')
    
    # Check for IPTC DigitalSourceType (Gemini/Google AI)
    for key, value in metadata.items():
        if 'digitalsourcetype' in key.lower() or 'iptc' in key.lower():
            if 'trainedmachine' in str(value).lower() or 'generative' in str(value).lower():
                detected.append('iptc ai marker')
                sources.append('IPTC metadata')
                break
    
    # Check for "parameters" key (A1111/ComfyUI specific)
    if any(key.lower() in ['parameters', 'png:parameters', 'prompt'] for key in metadata.keys()):
        if 'parameters' not in detected:
            detected.append('parameters metadata key')
            sources.append('PNG chunk')
    
    # Check for workflow JSON (ComfyUI specific)
    if any('workflow' in key.lower() for key in metadata.keys()):
        detected.append('comfyui workflow')
        sources.append('PNG metadata')
    
    # Check for prompt/negative prompt structure
    if 'negative prompt' in all_text or 'negative:' in all_text:
        if 'negative prompt' not in detected:
            detected.append('negative prompt structure')
            sources.append('metadata')
    
    # Determine confidence
    unique_detected = list(set(detected))
    
    if len(unique_detected) >= 3:
        confidence = "high"
    elif len(unique_detected) == 2:
        confidence = "medium"
    elif len(unique_detected) == 1:
        confidence = "low"
    else:
        confidence = "none"
    
    is_ai = confidence != "none"
    
    # Identify the AI tool
    ai_tool = identify_ai_tool(unique_detected, all_text) if is_ai else "None"
    
    return ScanResult(
        filepath=filepath,
        is_ai=is_ai,
        confidence=confidence,
        detected_signatures=unique_detected,
        metadata_source=", ".join(set(sources)) if sources else "none",
        ai_tool=ai_tool
    )


def scan_image(filepath: Path) -> ScanResult:
    """Scan a single image for AI signatures"""
    metadata = {}
    
    # Read PNG chunks directly (most reliable for SD images)
    if filepath.suffix.lower() == '.png':
        png_chunks = read_png_chunks(filepath)
        for key, value in png_chunks.items():
            metadata[f"PNG:{key}"] = value
    
    # Get EXIF data
    exif_data = get_exif_data(filepath)
    metadata.update(exif_data)
    
    # First check metadata-based detection
    result = check_for_ai_signatures(metadata, filepath)
    
    # If no metadata signatures found, check for visual/heuristic markers
    if not result.is_ai:
        detected = []
        sources = []
        ai_tool = "None"
        
        # Check for Gemini watermark (white star in corner)
        if check_gemini_watermark(filepath):
            detected.append('gemini watermark detected')
            sources.append('visual watermark')
            ai_tool = "Google Gemini"
        
        # Check for AI-typical dimensions with no EXIF (suspicious for ChatGPT/DALL-E)
        is_ai_dim, width, height = check_ai_dimensions(filepath)
        
        # Images with AI dimensions AND no EXIF are suspicious
        # (Real camera photos almost always have EXIF)
        has_no_exif = not exif_data or len([k for k in exif_data.keys() if not k.startswith('PNG:')]) == 0
        
        if is_ai_dim and has_no_exif:
            detected.append(f'ai-typical dimensions ({width}x{height}) with no EXIF')
            sources.append('dimension analysis')
            
            # 1024x1024 specifically is very common for DALL-E 3 / ChatGPT
            if width == 1024 and height == 1024 and ai_tool == "None":
                ai_tool = "ChatGPT (DALL-E 3) or Gemini"
        
        if detected:
            # Build new result with visual detection
            unique_detected = list(set(detected))
            confidence = "medium" if len(unique_detected) >= 2 else "low"
            
            return ScanResult(
                filepath=filepath,
                is_ai=True,
                confidence=confidence,
                detected_signatures=unique_detected,
                metadata_source=", ".join(set(sources)) if sources else "none",
                ai_tool=ai_tool
            )
    
    return result


def scan_folder(source_folder: str, verbose: bool = True) -> list[ScanResult]:
    """Scan all images in a folder"""
    source_path = Path(source_folder)
    results = []
    
    if not source_path.exists():
        print(f"Error: Source folder does not exist: {source_folder}")
        return results
    
    # Find all image files
    image_files = []
    for ext in IMAGE_EXTENSIONS:
        image_files.extend(source_path.glob(f"*{ext}"))
        image_files.extend(source_path.glob(f"*{ext.upper()}"))
    
    total = len(image_files)
    if verbose:
        print(f"Found {total} images to scan...")
    
    for i, filepath in enumerate(image_files, 1):
        if verbose and i % 10 == 0:
            print(f"  Scanning {i}/{total}...")
            
        result = scan_image(filepath)
        results.append(result)
    
    return results


def filter_ai_images(
    source_folder: str,
    ai_destination: str,
    move: bool = True,
    recursive: bool = False,
    min_confidence: str = "low",
    verbose: bool = True
) -> dict:
    """
    Main function to filter AI images from a folder
    
    Args:
        source_folder: Folder to scan for images
        ai_destination: Folder to move/copy AI images to
        move: True to move files, False to copy
        recursive: Scan subfolders recursively
        min_confidence: Minimum confidence level to consider ("low", "medium", "high")
        verbose: Print progress information
    
    Returns:
        Dictionary with statistics about the operation
    """
    source_path = Path(source_folder)
    dest_path = Path(ai_destination)
    
    # Validate paths
    if not source_path.exists():
        print(f"Error: Source folder does not exist: {source_folder}")
        return {}
    
    # Create destination if it doesn't exist
    dest_path.mkdir(parents=True, exist_ok=True)
    
    # Confidence levels
    confidence_levels = {"high": 3, "medium": 2, "low": 1, "none": 0}
    min_level = confidence_levels.get(min_confidence.lower(), 1)
    
    # Find all image files
    image_files = []
    if recursive:
        for ext in IMAGE_EXTENSIONS:
            image_files.extend(source_path.rglob(f"*{ext}"))
            image_files.extend(source_path.rglob(f"*{ext.upper()}"))
    else:
        for ext in IMAGE_EXTENSIONS:
            image_files.extend(source_path.glob(f"*{ext}"))
            image_files.extend(source_path.glob(f"*{ext.upper()}"))
    
    # Remove duplicates (case-insensitive extensions might cause this)
    image_files = list(set(image_files))
    
    total = len(image_files)
    if verbose:
        print(f"\n{'='*60}")
        print(f"AI Image Filter")
        print(f"{'='*60}")
        print(f"Source: {source_folder}")
        print(f"AI Destination: {ai_destination}")
        print(f"Mode: {'Move' if move else 'Copy'}")
        print(f"Minimum Confidence: {min_confidence}")
        print(f"{'='*60}")
        print(f"\nFound {total} images to scan...")
    
    # Statistics
    stats = {
        "total_scanned": total,
        "ai_detected": 0,
        "ai_high": 0,
        "ai_medium": 0,
        "ai_low": 0,
        "normal": 0,
        "errors": 0,
        "files_moved": [],
        "files_kept": [],
        "by_tool": {},  # Track counts by AI tool
    }
    
    for i, filepath in enumerate(image_files, 1):
        if verbose and (i % 25 == 0 or i == total):
            print(f"  Progress: {i}/{total} ({100*i//total}%)")
        
        try:
            result = scan_image(filepath)
            conf_level = confidence_levels.get(result.confidence, 0)
            
            if result.is_ai and conf_level >= min_level:
                # This is an AI image, move/copy it
                stats["ai_detected"] += 1
                
                if result.confidence == "high":
                    stats["ai_high"] += 1
                elif result.confidence == "medium":
                    stats["ai_medium"] += 1
                else:
                    stats["ai_low"] += 1
                
                # Track by AI tool
                tool = result.ai_tool
                if tool not in stats["by_tool"]:
                    stats["by_tool"][tool] = 0
                stats["by_tool"][tool] += 1
                
                # Determine destination path
                dest_file = dest_path / filepath.name
                
                # Handle name conflicts
                counter = 1
                while dest_file.exists():
                    stem = filepath.stem
                    dest_file = dest_path / f"{stem}_{counter}{filepath.suffix}"
                    counter += 1
                
                # Move or copy
                if move:
                    shutil.move(str(filepath), str(dest_file))
                else:
                    shutil.copy2(str(filepath), str(dest_file))
                
                stats["files_moved"].append({
                    "original": str(filepath),
                    "destination": str(dest_file),
                    "confidence": result.confidence,
                    "ai_tool": result.ai_tool,
                    "signatures": result.detected_signatures[:5]  # Limit for readability
                })
                
                if verbose:
                    action = "Moved" if move else "Copied"
                    print(f"    [{result.confidence.upper()}] [{result.ai_tool}] {action}: {filepath.name}")
                    
            else:
                stats["normal"] += 1
                stats["files_kept"].append(str(filepath))
                
        except Exception as e:
            stats["errors"] += 1
            if verbose:
                print(f"    Error processing {filepath.name}: {e}")
    
    # Print summary
    if verbose:
        print(f"\n{'='*60}")
        print(f"SUMMARY")
        print(f"{'='*60}")
        print(f"Total images scanned: {stats['total_scanned']}")
        print(f"AI images detected: {stats['ai_detected']}")
        print(f"  - High confidence: {stats['ai_high']}")
        print(f"  - Medium confidence: {stats['ai_medium']}")
        print(f"  - Low confidence: {stats['ai_low']}")
        print(f"Normal images: {stats['normal']}")
        print(f"Errors: {stats['errors']}")
        
        # Show breakdown by AI tool
        if stats["by_tool"]:
            print(f"\n{'='*60}")
            print(f"BREAKDOWN BY AI TOOL")
            print(f"{'='*60}")
            for tool, count in sorted(stats["by_tool"].items(), key=lambda x: -x[1]):
                print(f"  {tool}: {count}")
        
        print(f"{'='*60}\n")
    
    return stats


def main():
    """Interactive mode for the AI filter"""
    print("\n" + "="*60)
    print("  AI IMAGE FILTER")
    print("  Detect and sort AI-generated images")
    print("="*60 + "\n")
    
    # Get source folder
    while True:
        source = input("Enter the SOURCE folder to scan: ").strip()
        source = source.strip('"').strip("'")  # Remove quotes if pasted
        if os.path.isdir(source):
            break
        print(f"  Error: '{source}' is not a valid folder. Try again.\n")
    
    # Get destination folder
    while True:
        dest = input("Enter the DESTINATION folder for AI images: ").strip()
        dest = dest.strip('"').strip("'")
        if dest:
            break
        print("  Error: Destination cannot be empty. Try again.\n")
    
    # Options
    print("\n--- Options ---")
    
    move_choice = input("Move or Copy files? (m/c) [m]: ").strip().lower()
    move = move_choice != 'c'
    
    recursive_choice = input("Scan subfolders recursively? (y/n) [n]: ").strip().lower()
    recursive = recursive_choice == 'y'
    
    print("\nConfidence levels:")
    print("  - low: Detect any AI signature (may have false positives)")
    print("  - medium: Require 2+ signatures (balanced)")
    print("  - high: Require 3+ signatures (very confident)")
    confidence = input("Minimum confidence level? (low/medium/high) [low]: ").strip().lower()
    if confidence not in ['low', 'medium', 'high']:
        confidence = 'low'
    
    # Confirm
    print(f"\n--- Confirm ---")
    print(f"Source: {source}")
    print(f"Destination: {dest}")
    print(f"Mode: {'Move' if move else 'Copy'}")
    print(f"Recursive: {'Yes' if recursive else 'No'}")
    print(f"Min Confidence: {confidence}")
    
    confirm = input("\nProceed? (y/n): ").strip().lower()
    if confirm != 'y':
        print("Operation cancelled.")
        return
    
    # Run the filter
    filter_ai_images(
        source_folder=source,
        ai_destination=dest,
        move=move,
        recursive=recursive,
        min_confidence=confidence,
        verbose=True
    )
    
    print("Done! Press Enter to exit...")
    input()


if __name__ == "__main__":
    main()
